---

- name: install dnsmasq, a lightweight DHCP and caching DNS server
  apt: name=dnsmasq state=present

- template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.conf
#  notify: restart dnsmasq

- name: install hostapd, a IEEE 802.11 AP, IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
  apt: name=hostapd state=present

- template: src=hostapd.conf.j2 dest=/etc/hostapd/hostapd.conf
#  notify: restart hostapd

- name: Patch hostapd boot option
  lineinfile:
    dest: /etc/default/hostapd
    insertafter: '^#DAEMON_CONF='
    line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'

- lineinfile: dest=/etc/dhcpcd.conf line="denyinterfaces wlan1"

- name: install custom interfaces
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'

- name: add pre-configured outbound wlan networks
  blockinfile:
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    insertafter: EOF
    block: |
      network={
              ssid="{{ item.ssid }}"
              key_mgmt=WPA-PSK
              proto=WPA2
              pairwise=CCMP
              group=CCMP
              psk="{{ item.psk }}"
              priority={{ item.priority }}
      }
  with_items: '{{ outbound_access_points }}'