---

- name: Install dnsmasq, a lightweight DHCP and caching DNS server
  apt: name=dnsmasq state=present

- stat: path=/etc/dnsmasq.conf.orig
  register: st

- copy: remote_src=True src=/etc/dnsmasq.conf dest=/etc/dnsmasq.conf.orig
  when: not st.stat.exists

- template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.conf
  notify: restart dnsmasq

- name: Install hostapd, a IEEE 802.11 AP, IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
  apt: name=hostapd state=present

- template: src=hostapd.conf.j2 dest=/etc/hostapd/hostapd.conf
  notify: restart hostapd

- name: Patch hostapd boot option
  lineinfile:
    dest: /etc/default/hostapd
    insertafter: '^#DAEMON_CONF='
    line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'

- lineinfile: dest=/etc/dhcpcd.conf line="denyinterfaces wlan0"

- name: Patch WLAN interface
  replace:
    dest: /etc/network/interfaces
    regexp: 'iface wlan0 inet (manual|static)\n.*wpa_supplicant\.conf'
    replace: 'iface wlan0 inet static\n    address {{ rpi_wlan_ip_prefix }}1\n    netmask 255.255.255.0\n    network {{ rpi_wlan_ip_prefix }}0\n    broadcast {{ rpi_wlan_ip_prefix }}255\n#    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf'
  notify:
    - ifdown wlan
    - ifup wlan