---

- hosts: baaahs-lights-server
  roles:
    - setup
    - performance-optimizations
    - endurance-optimizations
    - wireless-configuration
    - ups-pico-setup
    - ola-install
    - baaahs-services
  become: yes
