---

- hosts: raspberry-pi-3-access-point
  roles:
    - setup
    - performance-optimizations
    - endurance-optimizations
    - ola-install
    - baaahs-lights-server-install
    - wifi-access-point-configuration
  become: yes
