---

- hosts: raspberry-pi-3-access-point
  roles:
    - setup
    - performance-optimizations
    - endurance-optimizations
    - wifi-access-point-configuration
    - ups-pico-setup
    - ola-install
    - baaahs-lights-server-install
  become: yes
