---

- name: Clone master branch of BAAAHS dmx-broadcaster
  git:
    repo: 'https://github.com/baaahs/single-value-dmx-broadcaster.git'
    dest: '{{ baaahs_dmx_broadcaster_install_dir }}'
    version: '{{ baaahs_dmx_broadcaster_checkout_branch }}'
    force: yes

- name: Change permissions of BAAAHS dmx-broadcaster source
  file:
    path: '{{ baaahs_dmx_broadcaster_install_dir }}'
    owner: '{{ baaahs_username }}'
    group: '{{ baaahs_username }}'
    recurse: yes

- name: install whiteout systemd unit file
  template:
    src: baaahs_whiteout.j2
    dest: /etc/systemd/system/whiteout.service

- name: start whiteout
  systemd:
    name: whiteout
    enabled: yes
    state: started
    daemon_reload: yes