---

- name: compute hashed baaahs user account password
  command: "openssl passwd -salt {{ openssl_salt }} -1 {{ baaahs_password }}"
  register: hashed_baaahs_password

- name: add baaahs user
  user:
    name: '{{ baaahs_username }}'
    shell: /bin/bash
    groups: "sudo,audio,video,i2c"
    append: yes
    password: "{{ hashed_baaahs_password.stdout }}"

- name: install package requirements for baaahs light server
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - libavahi-compat-libdnssd1
    - libasound2-dev

- name: install pip requirements for baaahs light server
  pip:
    name: "{{ item }}"
  with_items:
    - CherryPy
    - https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/pybonjour/pybonjour-1.1.1.zip
    - pyalsaaudio

- name: Clone master branch of BAAAHS lights
  git:
    repo: 'https://github.com/baaahs/lights.git'
    dest: '~/{{ baaahs_lights_install_dir }}'
    version: master
    force: yes
  become: true
  become_user: '{{ baaahs_username }}'

- name: change the mode from simulator to ola (currently dangerous)
  lineinfile:
    dest: '~/{{ baaahs_lights_install_dir }}/data/config.json'
    regexp: '"mode": "simulator",'
    line: '"mode": "ola",'
  become: true
  become_user: '{{ baaahs_username }}'

- name: install lights systemd unit file
  template:
    src: baaahs_lights.j2
    dest: /etc/systemd/system/lights.service

- name: start lights
  systemd:
    name: lights
    enabled: yes
    state: started
    daemon_reload: yes

- name: Clone master branch of BAAAHS OSC Layout Server
  git:
    repo: 'https://github.com/baaahs/osc-layout-server.git'
    dest: '~/{{ baaahs_layout_server_install_dir }}'
    version: master
    force: yes
  become: true
  become_user: '{{ baaahs_username }}'

- name: install osc layout server systemd unit file
  template:
    src: baaahs_osc_layout_server.j2
    dest: /etc/systemd/system/osc_layout_server.service

- name: start osc layout server
  systemd:
    name: osc_layout_server
    enabled: yes
    state: started
    daemon_reload: yes

- name: Clone master branch of BAAAHS cadence
  git:
    repo: 'https://github.com/baaahs/cadence.git'
    dest: '~/{{ baaahs_cadence_install_dir }}'
    version: master
    force: yes
  become: true
  become_user: '{{ baaahs_username }}'

- name: USB sound cards are registered as card 1
  lineinfile:
    dest: /usr/share/alsa/alsa.conf
    regexp: '^defaults.ctl.card 0'
    line: 'defaults.ctl.card 1'

- name: USB sound cards are registered as card 1
  lineinfile:
    dest: /usr/share/alsa/alsa.conf
    regexp: '^defaults.pcm.card 0'
    line: 'defaults.pcm.card 1'

- name: Install the readme
  template:
    src: readme.txt
    dest: ~/readme.txt
  become: true
  become_user: "{{ baaahs_username }}"