---

- name: compute hashed baaahs user account password
  command: "openssl passwd -salt {{ openssl_salt }} -1 {{ baaahs_password }}"
  register: hashed_baaahs_password

- name: add baaahs user
  user:
    name: '{{ baaahs_username }}'
    shell: /bin/bash
    groups: "sudo,audio,video,i2c"
    append: yes
    password: "{{ hashed_baaahs_password.stdout }}"

- name: enable passwordless sudo-ing for baaahs
  template:
    src: 011_baaahs-nopasswd.j2
    dest: /etc/sudoers.d/011_baaahs-nopasswd
    owner: root
    group: root
    mode: 'u+r,g+r'

- name: Install the readme
  template:
    src: readme.txt
    dest: '{{ baaahs_readme_destination }}'

- name: Change permissions of BAAAHS readme
  file:
    path: '{{ baaahs_readme_destination }}'
    owner: '{{ baaahs_username }}'
    group: '{{ baaahs_username }}'

- name: Install vimrc file
  template:
    src: vimrc
    dest: '{{ baaahs_vimrc_destination }}'
    owner: '{{ baaahs_username }}'
    group: '{{ baaahs_username }}'
    mode: 'u+r,g+r'

- include: cadence.yml
- include: dmx_broadcaster.yml
- include: light_server.yml
- include: osc_layout.yml
- include: web_control.yml