---

- name: install pip requirements
  pip:
    name: "{{ item }}"
  with_items:
  - CherryPy

- name: Clone master branch of BAAAHS OSC Layout Server
  git:
    repo: 'https://github.com/baaahs/osc-layout-server.git'
    dest: '{{ baaahs_layout_server_install_dir }}'
    version: master
    force: yes

- name: Change permissions of BAAAHS OSC Layout source
  file:
    path: '{{ baaahs_layout_server_install_dir }}'
    owner: '{{ baaahs_username }}'
    group: '{{ baaahs_username }}'
    recurse: yes

- name: install osc layout server systemd unit file
  template:
    src: baaahs_osc_layout_server.j2
    dest: /etc/systemd/system/osc_layout_server.service

- name: start osc layout server
  systemd:
    name: osc_layout_server
    enabled: yes
    state: started
    daemon_reload: yes