---

- name: add baaahs user
  user:
    name: '{{ baaahs_primary_username }}'
    shell: /bin/bash
    groups: sudo
    append: yes
    password: '{{ baaahs_primary_password }}'

- name: install pip requirements for baaahs light server
  pip:
    name: "{{ item }}"
  with_items:
    - CherryPy
    - https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/pybonjour/pybonjour-1.1.1.zip

- name: install package requirements for baaahs light server
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - libavahi-compat-libdnssd1
    - ola
    - ola-python

- name: Clone master branch of BAAAHS lights
  git:
    repo: 'https://github.com/baaahs/lights.git'
    dest: '~/{{ baaahs_git_install_local_dir }}'
    version: master
  become: true
  become_user: '{{ baaahs_primary_username }}'

- name: install baaahs_lights systemd unit file
  template: src=baaahs_lights.j2 dest=/etc/systemd/system/baaahs_lights.service

#- name: start baaahs_lights
#  systemd: state=started name=baaahs_lights daemon_reload=yes