---

- name: add baaahs user
  user:
    name: '{{ baaahs_primary_username }}'
    shell: /bin/bash
    groups: sudo
    append: yes
    password: '{{ baaahs_primary_password }}'

- name: install package requirements for baaahs light server
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - libavahi-compat-libdnssd1

- name: install pip requirements for baaahs light server
  pip:
    name: "{{ item }}"
  with_items:
    - CherryPy
    - https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/pybonjour/pybonjour-1.1.1.zip

- name: Clone master branch of BAAAHS lights
  git:
    repo: 'https://github.com/baaahs/lights.git'
    dest: '~/{{ baaahs_git_install_local_dir }}'
    version: master
    force: yes
  become: true
  become_user: '{{ baaahs_primary_username }}'

- name: change the mode from simulator to ola (currently dangerous)
  lineinfile:
    dest: '~/{{ baaahs_git_install_local_dir }}/data/config.json'
    regexp: '"mode": "simulator",'
    line: '"mode": "ola",'
  become: true
  become_user: '{{ baaahs_primary_username }}'

- name: install lights systemd unit file
  template:
    src: baaahs_lights.j2
    dest: /etc/systemd/system/lights.service

- name: start lights
  systemd:
    name: lights
    enabled: yes
    state: started
    daemon_reload: yes