timezone: US/Pacific
keyboard_layout: us
locale: en_US.UTF-8
sd_card_overlock: 100
rpi_wlan_ip_prefix: 172.24.1
rpi_wlan_ssid: baaahs
rpi_wlan_wpa_passphrase: baaahs2017
rpi_wlan_channel: 6
ola_version: 0.10.4
ola_server_name: BAAAHS Lights
ola_user_and_group: olad
baaahs_primary_username: baaahs
baaahs_primary_password: armadildo
baaahs_git_install_local_dir: lights
dmx_universe_name: usb-outbound-dmx
dmx_universe_id: 0
panda_wireless_adapter_oui: 9c:ef:d5