timezone: US/Pacific
keyboard_layout: us
locale: en_US.UTF-8
sd_card_overlock: 100
rpi_wlan_cidr: 172.24.1.0/24
rpi_wlan_interface_ip: "{{ rpi_wlan_cidr | ipaddr(1) | ipaddr('address') }}"
rpi_wlan_interface_network: "{{ rpi_wlan_cidr | ipaddr('network') }}"
rpi_wlan_interface_broadcast: "{{ rpi_wlan_cidr | ipaddr('broadcast') }}"
rpi_wlan_first_dhcp_ip: "{{ rpi_wlan_cidr  | ipaddr(10) | ipaddr('address') }}"
rpi_wlan_last_dhcp_ip: "{{ rpi_wlan_cidr  | ipaddr(-2) | ipaddr('address') }}"
rpi_wlan_ssid: baaahs
rpi_wlan_wpa_passphrase: baaahs2017
rpi_wlan_channel: 6
ola_version: 0.10.5
ola_server_name: BAAAHS Lights
ola_user_and_group: olad
openssl_salt: iritis_online_stem_clay_afro
baaahs_username: baaahs
baaahs_password: armadillo
baaahs_lights_install_dir: lights
baaahs_cadence_install_dir: cadence
baaahs_layout_server_install_dir: layout_server
baaahs_layout_server_layout_file: BAAAHS Main.touchosc
baaahs_ola_universe_watchdog: ola_universe_watchdog
dmx_universe_name: usb-outbound-dmx
dmx_universe_id: 0
panda_wireless_adapter_oui: 9c:ef:d5
raspberry_pi_foundation_adapter_oui: b8:27:eb
human_readable_server_name: BAAAHS Lights Server