timezone: US/Pacific
keyboard_layout: us
locale: en_US.UTF-8
sd_card_overlock: 100
rpi_wlan_cidr: 172.24.1.0/24
rpi_wlan_interface_ip: "{{ rpi_wlan_cidr | ipaddr(1) | ipaddr('address') }}"
rpi_wlan_interface_network: "{{ rpi_wlan_cidr | ipaddr('network') }}"
rpi_wlan_interface_broadcast: "{{ rpi_wlan_cidr | ipaddr('broadcast') }}"
rpi_wlan_first_dhcp_ip: "{{ rpi_wlan_cidr  | ipaddr(10) | ipaddr('address') }}"
rpi_wlan_last_dhcp_ip: "{{ rpi_wlan_cidr  | ipaddr(-2) | ipaddr('address') }}"
rpi_wlan_ssid: baaahs
rpi_wlan_wpa_passphrase: baaahs2017
rpi_wlan_channel: 6
ola_version: 0.10.4
ola_server_name: BAAAHS Lights
ola_user_and_group: olad
baaahs_primary_username: baaahs
baaahs_primary_password: armadildo
baaahs_git_install_local_dir: lights
baaahs_layout_server_install_local_dir: layout_server
baaahs_ola_universe_watchdog: ola_universe_watchdog
dmx_universe_name: usb-outbound-dmx
dmx_universe_id: 0
panda_wireless_adapter_oui: 9c:ef:d5
raspberry_pi_foundation_adapter_oui: b8:27:eb