---

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: restart hostapd
  service:
    name: hostapd
    state: restarted

- name: restart wlan0
  shell: "ifdown wlan0 && ifup wlan0"

- name: restart wlan1
  shell: "ifdown wlan1 && ifup wlan1"