---

- name: install pip requirements for BAAAHS OSC layout server
  pip:
    name: "{{ item }}"
  with_items:
    - cachetools

- name: Clone master branch of BAAAHS OSC Layout Server
  git:
    repo: 'https://github.com/baaahs/osc-layout-server.git'
    dest: '~/{{ baaahs_layout_server_install_local_dir }}'
    version: master
    force: yes
  become: true
  become_user: '{{ baaahs_primary_username }}'

- name: install osc layout server systemd unit file
  template:
    src: baaahs_osc_layout_server.j2
    dest: /etc/systemd/system/osc_layout_server.service

- name: start osc layout server
  systemd:
    name: osc_layout_server
    enabled: yes
    state: started
    daemon_reload: yes