---

- name: USB sound cards are registered as card 1
  lineinfile:
    dest: /etc/default/keyboard
    regexp: '^defaults.ctl.card 0'
    line: 'defaults.ctl.card 1'

- name: USB sound cards are registered as card 1
  lineinfile:
    dest: /etc/default/keyboard
    regexp: '^defaults.pcm.card 0'
    line: 'defaults.pcm.card 1'

- name: install package requirements
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - libasound2-dev

- name: install pip requirements
  pip:
    name: "{{ item }}"
  with_items:
    - pyalsaaudio