---

- name: restart dnsmasq
  service: name=dnsmasq state=restarted

- name: restart hostapd
  service: name=hostapd state=restarted

- name: ifdown wlan
  shell: "ifdown wlan0"

- name: ifup wlan
  shell: "ifup wlan0"