---

- name: Detect if olad is already installed
  command: which olad
  changed_when: false
  failed_when: false
  register: ola_installed

- name: Install packages required to compile openlighting alliance source
  apt: name={{item}} state=installed
  with_items:
       - debhelper
       - autotools-dev
       - dh-autoreconf
       - bash-completion
       - libcppunit-dev
       - bison
       - flex
       - pkg-config
       - uuid-dev
       - python
       - python-protobuf
       - python-numpy
       - libprotobuf-dev
       - protobuf-compiler
       - libprotoc-dev
       - libusb-1.0-0-dev
       - libftdi-dev
       - liblo-dev
       - libmicrohttpd-dev
       - libncurses5-dev
  when: ola_installed|failed

- name: download and extract openlighting alliance source code
  unarchive:
    src: 'https://github.com/OpenLightingProject/ola/releases/download/{{ ola_version }}/ola-{{ ola_version }}.tar.gz'
    dest: /tmp
    remote_src: True
  when: ola_installed|failed

- name: alert user that preparations and compilation of ola take about 25-30 minutes
  pause:
    prompt: 'The next operation will configure and compile OLA on the PI. These operations take about 25-30 minutes to complete.'
    seconds: 5
  when: ola_installed|failed

- name: Build openlighting alliance source code
  command: '{{ item }}'
  args:
    chdir: '/tmp/ola-{{ ola_version }}'
  with_items:
    - ./configure --enable-python-libs --disable-all-plugins --enable-usbpro
    - make all
    - make install
    - ldconfig
  when: ola_installed|failed

- name: create olad group account
  group:
    name: '{{ ola_user_and_group }}'
    state: present
    system: yes

- name: create olad user account
  user:
    name: '{{ ola_user_and_group }}'
    state: present
    groups: '{{ ola_user_and_group }},dialout'
    system: yes

- name: create olad configuration directory
  file:
    path: /etc/ola
    state: directory
    mode: 'u=rwx,g=rx,o=rx'
    owner: '{{ ola_user_and_group }}'
    group: '{{ ola_user_and_group }}'

- name: install olad server configuration
  template:
    src: ola-server.conf.j2
    dest: /etc/ola/ola-server.conf
    owner: '{{ ola_user_and_group }}'
    group: '{{ ola_user_and_group }}'

- name: install olad usbserial plugin configuration
  template:
    src: ola-usbserial.conf.j2
    dest: /etc/ola/ola-usbserial.conf
    owner: '{{ ola_user_and_group }}'
    group: '{{ ola_user_and_group }}'

- name: install olad systemd file
  template:
    src: olad.j2
    dest: /etc/systemd/system/olad.service

- name: start olad
  systemd:
    name: olad
    enabled: yes
    state: started
    daemon_reload: yes