---

- name: Detect if olad is already installed
  command: which olad
  changed_when: false
  failed_when: false
  register: ola_installed

- name: Install packages required to compile openlighting alliance source
  apt: name={{item}} state=installed
  with_items:
       - debhelper
       - autotools-dev
       - dh-autoreconf
       - bash-completion
       - libcppunit-dev
       - bison
       - flex
       - pkg-config
       - uuid-dev
       - python
       - python-protobuf
       - python-numpy
       - libprotobuf-dev
       - protobuf-compiler
       - libprotoc-dev
       - libusb-1.0-0-dev
       - libftdi-dev
       - liblo-dev
       - libmicrohttpd-dev
       - libncurses5-dev
  when: ola_installed|failed

- name: download and extract openlighting alliance source code
  unarchive:
    src: 'https://github.com/OpenLightingProject/ola/releases/download/{{ ola_version }}/ola-{{ ola_version }}.tar.gz'
    dest: /tmp
    remote_src: True
  when: ola_installed|failed

- name: prepare openlighting alliance source code
  command: ./configure --enable-python-libs
  args:
    chdir: '/tmp/ola-{{ ola_version }}'
  when: ola_installed|failed

- name: Build openlighting alliance source code
  command: make {{ item }}
  args:
    chdir: '/tmp/ola-{{ ola_version }}'
  with_items:
    - all
    - install
  when: ola_installed|failed