---

- name: Update all packages to the latest version
  apt:
    update_cache: yes
    upgrade: dist

- name: setting locale to {{ locale }}
  locale_gen:
    name: '{{ locale }}'
    state: present

- name: set timezone to {{ timezone }}
  timezone: name={{ timezone }}

- name: set keyboard layout to {{ keyboard_layout }}
  lineinfile:
    dest: /etc/default/keyboard
    regexp: '^XKBLAYOUT=.*$'
    line: 'XKBLAYOUT="{{ keyboard_layout }}"'
  register: keyboard_layout_result

- name: activate keyboard layout {{ keyboard_layout }}
  shell: "dpkg-reconfigure -f noninteractive keyboard-configuration"
  when: keyboard_layout_result.changed

- name: install basic set of packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - git
    - rpi-update
    - vim
    - htop
    - python-pip
    - ola
    - ola-python

- name: run rpi-update
  shell: rpi-update

- name: Adding banner info in sshd.conf
  lineinfile: dest=/etc/ssh/sshd_config regexp='#Banner /etc/issue.net' line="Banner /etc/issue.net"

- name: Update ssh banner
  template: src=ssh-banner.j2 dest=/etc/issue.net

- name: Restart ssh
  service: name=ssh state=restarted