---

- name: install python RPI GPIO
  apt:
    pkg: python-rpi.gpio
    state: latest

- name: install ups pico required packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
       - python-dev
       - python-serial
       - python-smbus
       - python-jinja2
       - python-xmltodict
       - python-psutil

- name: Install xmltodict
  pip:
    name: xmltodict

- name: eable the ARM I2C interface
  lineinfile:
    dest: /boot/config.txt
    regexp: '^#dtparam=i2c_arm=on'
    line: 'dtparam=i2c_arm=on'

- name: disable the serial port
  lineinfile:
    path: /boot/config.txt
    insertafter: EOF
    line: enable_uart=0

- name: clone PiModules project
  git:
    repo: 'https://github.com/modmypi/PiModules.git'
    dest: /tmp/pymodules

- name: Install the email broadcasting package (required)
  command: python setup.py install
  args:
    chdir: /tmp/pymodules/code/python/package

- name: Install the System Monitoring & File Safe Shutdown Daemons
  command: python setup.py install
  args:
    chdir: /tmp/pymodules/code/python/upspico/picofssd

- name: Install the pico status script
  copy:
    src: /tmp/pymodules/pico_status/pico_status_hv3.0.py
    dest: /usr/local/bin/pico_status_hv3.0.py
    owner: root
    group: root
    remote_src: True
    mode: "u=rwx,g=rx,o=rx"

- name: enable pico fssd
  service:
    name: picofssd
    enabled: yes
    state: started

- name: Install the UPS PIco HV3.0 Hardware RTC
  apt:
    pkg: i2c-tools
    state: latest

- name: Enable modules
  blockinfile:
    path: /etc/modules
    insertbefore: EOF
    block: |
      i2c-bcm2708
      i2c-dev
      rtc-ds1307

- name: Enable RTC
  blockinfile:
    path: /etc/rc.local
    insertbefore: exit 0
    block: |
      echo ds1307 0x68 > /sys/class/i2c-adapter/i2c-1/new_device
      ( sleep 4; hwclock -s ) &
